version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - errcheck

formatters:
  settings:
    gci:
      sections:
        - standard # Captures all standard packages if they do not match another section.
        - default # Contains all imports that could not be matched to another section type.
        - prefix(github/thought-machine/prometheus-cardinality-exporter)
