run:
  timeout: 5m

issues:

linters:
  disable:
    # Should fix the issues and re-enable this linter
    - errcheck

linters-settings:
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/thought-machine/please)
