# alpine:3.18.0
FROM alpine@sha256:c0669ef34cdc14332c0f1ab0c2c01acb91d96014b172f1a76f3a39e63d1f0bda

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

COPY /prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

RUN chmod +x /home/app/prometheus-cardinality-exporter

USER app

EXPOSE 9090

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
