# 1.24.2-alpine3.21 (linux/amd64)
FROM golang:1.24.4-alpine3.21@sha256:56a23791af0f77c87b049230ead03bd8c3ad41683415ea4595e84ce7eada121a as builder

RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /go/github.com/thought-machine/prometheus-cardinality-exporter

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" .

# alpine:3.21.3 (linux/amd64)
FROM alpine@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715

EXPOSE 9090

COPY --from=builder /go/github.com/thought-machine/prometheus-cardinality-exporter/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

RUN chmod +x /home/app/prometheus-cardinality-exporter

USER app

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
