# 1.23.4-alpine3.21
FROM golang@sha256:6c5c9590f169f77c8046e45c611d3b28fe477789acd8d3762d23d4744de69812 as builder

RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /go/github.com/thought-machine/prometheus-cardinality-exporter

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" .

FROM scratch

EXPOSE 9090

COPY --from=builder /go/github.com/thought-machine/prometheus-cardinality-exporter/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

USER 255999

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
