# 1.26.2-alpine3.23 (linux/amd64)
FROM golang:1.27.1-alpine3.23@sha256:d9e2f2f07b10cc922da3e80e035c3058810b328d5aef82d2c63680967c5e2ec9 AS builder

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /app

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" -o prometheus-cardinality-exporter .

FROM scratch

EXPOSE 9090

COPY --from=builder /app/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

USER 255999

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
