# 1.24.1-alpine3.21 (linux/amd64)
FROM golang@sha256:52ff1b35ff8de185bf9fd26c70077190cd0bed1e9f16a2d498ce907e5c421268 as builder

RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /go/github.com/thought-machine/prometheus-cardinality-exporter

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" .

# alpine:3.21.3 (linux/amd64)
FROM alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

EXPOSE 9090

COPY --from=builder /go/github.com/thought-machine/prometheus-cardinality-exporter/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

RUN chmod +x /home/app/prometheus-cardinality-exporter

USER app

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
