# digest for alpine:3.14.2
FROM alpine@sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

COPY /prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

RUN chmod +x /home/app/prometheus-cardinality-exporter

USER app

EXPOSE 9090

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
