go_library(
    name = "mock_cardinality",
    srcs = [
        "mock_cardinality.go",
    ],
    visibility = ["//..."],
    deps = [
        "//third_party/go:prometheus",
        "//third_party/go:mock",
    ],
)
